manipulator:
    type: position_controllers/JointTrajectoryController
    default: True
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50